
import img1 from '../assets/img1.jpg';
import img2 from '../assets/img2.jpg';
import img3 from '../assets/img3.jpg';
import img4 from '../assets/img4.jpg';
import img5 from '../assets/img5.jpg';
import img6 from '../assets/img6.jpg';
import img7 from '../assets/img7.jpg';
import img8 from '../assets/img8.jpg';
import img9 from '../assets/img9.jpg';
import img10 from '../assets/img10.jpg';
import img11 from '../assets/img11.jpg';
import img12 from '../assets/img12.jpg';
import img13 from '../assets/img13.jpg';
import img14 from '../assets/img14.jpg';
import img15 from '../assets/img15.jpg';
import img16 from '../assets/img16.jpg';
import img17 from '../assets/img17.jpg';
import img18 from '../assets/img18.jpg';
import img19 from '../assets/img19.jpg';
import img20 from '../assets/img20.jpg';
import img21 from '../assets/img21.jpg';
import img22 from '../assets/img22.jpg';
import img23 from '../assets/img23.jpg';
import img24 from '../assets/img24.jpg';
import img25 from '../assets/img25.jpg';
import img26 from '../assets/img26.jpg';
import img27 from '../assets/img27.jpg';
import img28 from '../assets/img28.jpg';
import img29 from '../assets/img29.jpg';
import img30 from '../assets/img30.jpg';
import img31 from '../assets/img31.jpg';
import img32 from '../assets/img32.jpg';
import img33 from '../assets/img33.jpg';
import img34 from '../assets/img34.jpg';
import img35 from '../assets/img35.jpg';
import img36 from '../assets/img36.jpg';
import img37 from '../assets/img37.jpg';
import img38 from '../assets/img38.jpg';
import img39 from '../assets/img39.jpg';
import img40 from '../assets/img40.jpg';
import img41 from '../assets/img41.jpg';
import img42 from '../assets/img42.jpg';
import img43 from '../assets/img43.jpg';
import img44 from '../assets/img44.jpg';
import img45 from '../assets/img45.jpg';

let imageStore=[];
imageStore.push(img1);
imageStore.push(img2);
imageStore.push(img3);
imageStore.push(img4);
imageStore.push(img5);
imageStore.push(img6);
imageStore.push(img7);
imageStore.push(img8);
imageStore.push(img9);
imageStore.push(img10);
imageStore.push(img11);
imageStore.push(img12);
imageStore.push(img13);
imageStore.push(img14);
imageStore.push(img15);
imageStore.push(img16);
imageStore.push(img17);
imageStore.push(img18);
imageStore.push(img19);
imageStore.push(img20);
imageStore.push(img21);
imageStore.push(img22);
imageStore.push(img23);
imageStore.push(img24);
imageStore.push(img25);
imageStore.push(img26);
imageStore.push(img27);
imageStore.push(img28);
imageStore.push(img29);
imageStore.push(img30);
imageStore.push(img31);
imageStore.push(img32);
imageStore.push(img33);
imageStore.push(img34);
imageStore.push(img35);
imageStore.push(img36);
imageStore.push(img37);
imageStore.push(img38);
imageStore.push(img39);
imageStore.push(img40);
imageStore.push(img41);
imageStore.push(img42);
imageStore.push(img43);
imageStore.push(img44);
imageStore.push(img45);

export default imageStore;