
import img1 from '../assets/img1.jpg';
import img2 from '../assets/img2.jpg';
import img3 from '../assets/img3.jpg';
import img4 from '../assets/img4.jpg';
import img5 from '../assets/img5.jpg';
import img6 from '../assets/img6.jpg';
import img7 from '../assets/img7.jpg';
import img8 from '../assets/img8.jpg';
import img9 from '../assets/img9.jpg';
import img10 from '../assets/img10.jpg';
import img11 from '../assets/img11.jpg';
import img12 from '../assets/img12.jpg';
import img13 from '../assets/img13.jpg';
import img14 from '../assets/img14.jpg';
import img15 from '../assets/img15.jpg';
import img16 from '../assets/img16.jpg';
import img17 from '../assets/img17.jpg';
import img18 from '../assets/img18.jpg';
import img19 from '../assets/img19.jpg';
import img20 from '../assets/img20.jpg';
import img21 from '../assets/img21.jpg';
import img22 from '../assets/img22.jpg';
import img23 from '../assets/img23.jpg';
import img24 from '../assets/img24.jpg';
import img25 from '../assets/img25.jpg';

let imageStore=[];
imageStore.push(img1);
imageStore.push(img2);
imageStore.push(img3);
imageStore.push(img4);
imageStore.push(img5);
imageStore.push(img6);
imageStore.push(img7);
imageStore.push(img8);
imageStore.push(img9);
imageStore.push(img10);
imageStore.push(img11);
imageStore.push(img12);
imageStore.push(img13);
imageStore.push(img14);
imageStore.push(img15);
imageStore.push(img16);
imageStore.push(img17);
imageStore.push(img18);
imageStore.push(img19);
imageStore.push(img20);
imageStore.push(img21);
imageStore.push(img22);
imageStore.push(img23);
imageStore.push(img24);
imageStore.push(img25);

export default imageStore;